#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="webDB1")]
public partial class DataClasses2DataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertdata_analysis(data_analysis instance);
  partial void Updatedata_analysis(data_analysis instance);
  partial void Deletedata_analysis(data_analysis instance);
  #endregion
	
	public DataClasses2DataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClasses2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<data_analysis> data_analysis
	{
		get
		{
			return this.GetTable<data_analysis>();
		}
	}
	
	[Function(Name="dbo.nweXMLfile")]
	public int nweXMLfile([Parameter(Name="UserID", DbType="Int")] System.Nullable<int> userID, [Parameter(DbType="Xml")] System.Xml.Linq.XElement xmlfile)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, xmlfile);
		return ((int)(result.ReturnValue));
	}
}

[Table(Name="dbo.data_analysis")]
public partial class data_analysis : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _xmlfile_id;
	
	private int _UserID;
	
	private string _xmlfile;
	
	private System.Nullable<System.DateTime> _date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onxmlfile_idChanging(int value);
    partial void Onxmlfile_idChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnxmlfileChanging(string value);
    partial void OnxmlfileChanged();
    partial void OndateChanging(System.Nullable<System.DateTime> value);
    partial void OndateChanged();
    #endregion
	
	public data_analysis()
	{
		OnCreated();
	}
	
	[Column(Storage="_xmlfile_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int xmlfile_id
	{
		get
		{
			return this._xmlfile_id;
		}
		set
		{
			if ((this._xmlfile_id != value))
			{
				this.Onxmlfile_idChanging(value);
				this.SendPropertyChanging();
				this._xmlfile_id = value;
				this.SendPropertyChanged("xmlfile_id");
				this.Onxmlfile_idChanged();
			}
		}
	}
	
	[Column(Storage="_UserID", DbType="Int NOT NULL")]
	public int UserID
	{
		get
		{
			return this._UserID;
		}
		set
		{
			if ((this._UserID != value))
			{
				this.OnUserIDChanging(value);
				this.SendPropertyChanging();
				this._UserID = value;
				this.SendPropertyChanged("UserID");
				this.OnUserIDChanged();
			}
		}
	}
	
	[Column(Storage="_xmlfile", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string xmlfile
	{
		get
		{
			return this._xmlfile;
		}
		set
		{
			if ((this._xmlfile != value))
			{
				this.OnxmlfileChanging(value);
				this.SendPropertyChanging();
				this._xmlfile = value;
				this.SendPropertyChanged("xmlfile");
				this.OnxmlfileChanged();
			}
		}
	}
	
	[Column(Storage="_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
